name: Backend CI (Spring Boot)

on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./vetcita-backend

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Compilar con Maven
        run: mvn clean package -DskipTests